### ISSUE TITLE
mirge3 gets killed

### ISSUE THREAD

**Issue by lchall08** [mhalushka/miRge3.0#101]
Running mirge3 on Rat samples: Goes through all the steps until novel miRNAs prediction and throws this error and stops.

Traceback (most recent call last):
  File "/opt/conda/envs/mirge3/bin/miRge3.0", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/conda/envs/mirge3/lib/python3.12/site-packages/mirge/__main__.py", line 203, in main
    predict_nmir(args, workDir, ref_db, base_names, pdUnmapped)
  File "/opt/conda/envs/mirge3/lib/python3.12/site-packages/mirge/libs/novel_mir.py", line 424, in predict_nmir
    generate_featureFiles(str(Path(outputdir2)), files, chrSeqDic, chrSeqLenDic, miRNAchrCoordivateDic, exactmiRNASeqDic)
  File "/opt/conda/envs/mirge3/lib/python3.12/site-packages/mirge/libs/generate_featureFiles.py", line 226, in generate_featureFiles
    features = clusterInstance.calculateFeature()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/mirge3/lib/python3.12/site-packages/mirge/classes/readCluster.py", line 320, in calculateFeature
    neclueotideCountList = neclueotideCountList + [templateNucleotide, count_TemplateNucleotide_percentage, count_nonTemplateNucleotide_percentage, count_A_percentage, count_T_percentage, count_C_percentage, count_G_percentage]
                                                                                                                                                    ^^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'count_A_percentage' where it is not associated with a value

**Comment by arunhpatil** [comment]
Hi @lchall08, 

I checked the error and it is wierd since `count_A_percentage` is pre-assigned. 
1. Can you check (the output) if the annotations and summary of miRNA reads are yielding abundant miRNAs, `without (or prior to) Novel miRNA predictions`. 
2. If adapters are not a problem in the previous step then I like to check the bug with your dataset. Can you share the file or subset which was used here? (Also, it would give more clarity if you could share the command used along with parameters, and you can rename your sample names if you choose).

Thank you,
Arun

**Comment by lchall08** [comment]
[annotation.report.csv](https://github.com/user-attachments/files/17248634/annotation.report.csv)

See attached the annotation report. 
This error is relatively new. I was previously able to run it successfully with a mouse dataset and this one is Rat so originally I thought it may be a bug in the library but nothing I can tell.

The code I used is:
miRge3.0 -s input.txt -db miRBase -lib /research/miRge3_Lib -on rat -cpu 50 -tcf -bam -o output -dex -mdt 1432_samplesheet_1.csv -a TGGAATTCTCGGGTGCCAAGG -NX -nmir


input.txt is just a list of all the fastqs

**Comment by arunhpatil** [comment]
Hi @lchall08, 

The summary looks Ok. At this stage we wont know at which file's (samples') processing we encountered this error. Can you run them in batches to isolate the file that caused the error? and if you could share that file or subset, I can take a look at the bug. 

Thank you,
Arun.

**Comment by lchall08** [comment]
Hi Arun,
Please see attached a subset of the files. I did a couple of extra tests to
figure out where the bug was:
1) The code always crashes at the novel miRNA prediction stage,
irrespective of which subset of data that I use. I was able to "finish" to
completion if I removed the -nmir option from my code. I put finish in
quotes since the miRNA_visualization did not populate, but the downstream
DESeq analysis etc. finished with no errors.
2) I really think this is happening only with using the rat reference
library as I do not have any issues running my other projects based on
mouse data. On this hunch, I used this same data but instead of "on rat" I
used "on mouse" and it ran with no issues at all.

Any thoughts?
Thank you for helping troubleshoot this.
 BAT_Leptin60_S1_L001_R1_001.fastq.gz
<https://drive.google.com/file/d/1MSD-gwummHwuz12o4XdGiFf98Dbju7Cz/view?usp=drive_web>
 Sham_1_S21_L001_R1_001.fastq.gz
<https://drive.google.com/file/d/1TujTATE-bzDf3CwXcGntbcVMSkQk112h/view?usp=drive_web>

**Comment by arunhpatil** [comment]
Hi @lchall08, 

I have used the Rat genome (`9c537e8c369cfcb2c33f9bed3b9af2c1  rat.tar.gz => md5sum value`) and was able to run miRge3.0 successfully. I suggest you download the reference and try the run again. You can also check for md5sum of the tar.gz file. 

Also, I skipped the DEX at this point as I didn't have metadata. Can you try the same samples without DEX and let me know if it works.

The version of the packages used are listed below:
```
bowtie version: 1.2.3
cutadapt version: 4.2
Samtools version: 1.6
RNAfold version: 2.4.14
```

I guess that the Rat reference is not extracted fully. I am sending the output folder via gmail. Let me know how it works.

Thank you,
Arun.
