### ISSUE TITLE
Issue running 

### ISSUE THREAD

**Issue by denise0593** [mhalushka/miRge3.0#106]
Dear, 
I have installed miRge with conda and running the following command:

`miRge3.0 -s fastq.gz -db miRBase -lib miRge3_Lib -on human -o mirge -gff -nmir -a AACTGTAGGCACCATCAAT -qumi -umi 0,12  -udd`

but I'm receiving the following error:

 BiopythonDeprecationWarning: Bio.pairwise2 has been deprecated, and we intend to remove it in a future rel
ease of Biopython. As an alternative, please consider using Bio.Align.PairwiseAligner as a replacement, and contact the Biopython developers if you still need the Bio.pairwise2 modu
le.
  warnings.warn(
bowtie version: 1.3.1
cutadapt version: 2.7
Samtools version: 1.19.2
RNAfold version: 2.7.0
Collecting and validating input files...

miRge3.0 will process 1 out of 1 input file(s).

concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/*****/miniconda3/lib/python3.11/concurrent/futures/process.py", line 261, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/*****/miniconda3/lib/python3.11/site-packages/mirge/libs/digest.py", line 331, in cutadapt
    fqreads = modifier(fqreads, matches)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/*****/miniconda3/lib/python3.11/site-packages/cutadapt/modifiers.py", line 210, in __call__
    info.matches.extend(matches)  # TODO extend or overwrite?
    ^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'matches'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/*****/miniconda3/bin/miRge3.0", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/*****/miniconda3/lib/python3.11/site-packages/mirge/__main__.py", line 140, in main
    pdDataFrame,sampleReadCounts,trimmedReadCounts,trimmedReadCountsUnique = baking(args, fastq_fullPath, base_names, workDir)
                                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/*****/miniconda3/lib/python3.11/site-packages/mirge/libs/digest.py", line 142, in baking
    a , b = fqres_pairs.result()
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/*****/miniconda3/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/*****/miniconda3/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
AttributeError: 'list' object has no attribute 'matches'

**Comment by arunhpatil** [comment]
Hi @denise0593,

I see that Cutadapt version is 2.7. Can you update it to the latest one? 

Is this installed on Mac OS?

Thank you,
Arun.

**Comment by denise0593** [comment]
Dear @arunhpatil, 
I've update the cutadapt version and now it works! 
Thanks a lot,
Denise
