### ISSUE TITLE
UnboundLocalError: local variable 'pre_name' referenced before assignment

### ISSUE THREAD

**Issue by TmrSegev** [mhalushka/miRge3.0#107]
Hi, 

I recently used mirge-build to add a new species, and when running miRge, I encountered the following error, which prevents the creation of the GFF file:

Summarizing and tabulating results...
Traceback (most recent call last):
  File "/home/stome/.local/bin/miRge3.0", line 8, in <module>
    sys.exit(main())
  File "/home/stome/.local/lib/python3.8/site-packages/mirge/_main_.py", line 166, in main
    summarize(args, workDir, ref_db, base_names, pdMapped, sampleReadCounts, trimmedReadCounts, trimmedReadCountsUnique)
  File "/home/stome/.local/lib/python3.8/site-packages/mirge/libs/summary.py", line 839, in summarize
    create_gff(args, pre_mirDict, mirDict, d, filenamegff, cannonical_4gff, isomirs_4gff, base_names, ref_db, annotation_lib, workDir, mirRPM_completeSet)
  File "/home/stome/.local/lib/python3.8/site-packages/mirge/libs/summary.py", line 120, in create_gff
    pre_cur_name[mature_name] = pre_name
UnboundLocalError: local variable 'pre_name' referenced before assignment

Could you please help me identify the issue? We followed the requirements in the documentation for mirge-build, but we are having difficulty pinpointing the problem.
Thank you,
Tomer

**Comment by arunhpatil** [comment]
Hi @TmrSegev,

I missed your message during the holidays. Were you able to fix it? I think this is the issue commonly found in iOS. If that is the case, let me know I will find a fix (Are you testing this on Mac?). I apologies for not getting back to you on this earlier. 

Thank you,
Arun.

**Comment by TmrSegev** [comment]
Hi,

Thank you for the response!
We managed to fix it by adapting our GFF file format to the exact GFF3 format you used for homo sapiens.
