### ISSUE TITLE
ValueError: `bins` must be positive, when an integer

### ISSUE THREAD

**Issue by xuanblo** [mhalushka/miRge3.0#11]
miRge3.0 -cpu 5 -s liver/SRR8487219.fastq.gz -on human -trf -o result/SRR8487219 -lib miRge3_Lib -db miRBase -dex
bowtie version: 1.3.0
cutadapt version: 2.6
Samtools version: 1.11
Collecting and validating input files...

miRge3.0 will process 1 out of 1 input file(s).

Cutadapt finished for file SRR8487219 in 140.269 second(s)
Collapsing finished for file SRR8487219 in 1.2128 second(s)

Matrix creation finished in 1.0541 second(s)

Traceback (most recent call last):
  File "/data/zhangxuan/miniconda3/envs/trfs/bin/miRge3.0", line 10, in <module>
    sys.exit(main())
  File "/data/zhangxuan/miniconda3/envs/trfs/lib/python3.7/site-packages/mirge/__main__.py", line 93, in main
    pdDataFrame,sampleReadCounts,trimmedReadCounts,trimmedReadCountsUnique = baking(args, fastq_fullPath, base_names, workDir)
  File "/data/zhangxuan/miniconda3/envs/trfs/lib/python3.7/site-packages/mirge/libs/digest.py", line 286, in baking
    hist, bins = np.histogram(val, bins=(maxVal-minVal))
  File "<__array_function__ internals>", line 6, in histogram
  File "/data/zhangxuan/miniconda3/envs/trfs/lib/python3.7/site-packages/numpy/lib/histograms.py", line 792, in histogram
    bin_edges, uniform_bins = _get_bin_edges(a, bins, range, weights)
  File "/data/zhangxuan/miniconda3/envs/trfs/lib/python3.7/site-packages/numpy/lib/histograms.py", line 424, in _get_bin_edges
    raise ValueError('`bins` must be positive, when an integer')
ValueError: `bins` must be positive, when an integer

**Comment by arunhpatil** [comment]
@xuanblo, I tried to replicate the error on my end (however, it was a successful run) and I have few things to check to resolve this issue:  Can you rerun miRge3.0 with ` -a TGGAATTCTCGGGTGCCAAGGAACTCCAG`? I suspect that is due to either adapter trimming step or that the file may be truncated. Since this issue occurs before alignment, parameters `-trf` and `-dex` should not affect.

**Comment by xuanblo** [comment]
@arunhpatil After I add `-a illumina`, miRge3.0 runs successfully. Thank you very much for your help!
