### ISSUE TITLE
Is my code working

### ISSUE THREAD

**Issue by tetty988** [mhalushka/miRge3.0#42]
Hi I am new to Linux and programming. I try to figure out how to analyze the miRNA seq data. I chose miRge3.0 for my first try because there are very clear instructions on line. 
I got the below running log. It is not like what I saw in the User guide. I am not sure what went wrong. 

bowtie version: 1.2.3
cutadapt version: 4.0
Samtools version: 1.10
Collecting and validating input files...

miRge3.0 will process 1 out of 1 input file(s).

Traceback (most recent call last):
  File "/home/staticeel/.local/bin/miRge3.0", line 8, in <module>
    sys.exit(main())
  File "/home/staticeel/.local/lib/python3.8/site-packages/mirge/__main__.py", line 103, in main
    pdDataFrame,sampleReadCounts,trimmedReadCounts,trimmedReadCountsUnique = baking(args, fastq_fullPath, base_names, workDir)
  File "/home/staticeel/.local/lib/python3.8/site-packages/mirge/libs/digest.py", line 133, in baking
    with dnaio.open(FQfile, mode='r') as readers:
  File "/home/staticeel/.local/lib/python3.8/site-packages/dnaio/__init__.py", line 139, in open
    return _open_single(
  File "/home/staticeel/.local/lib/python3.8/site-packages/dnaio/singleend.py", line 75, in _open_single
    return FastqReader(file, _close_file=close_file)
  File "/home/staticeel/.local/lib/python3.8/site-packages/dnaio/readers.py", line 149, in __init__
    th = next(self._iter)
  File "src/dnaio/_core.pyx", line 508, in dnaio._core.FastqIter.__next__
  File "src/dnaio/_core.pyx", line 443, in dnaio._core.FastqIter._read_into_buffer
  File "/usr/lib/python3.8/gzip.py", line 292, in read
    return self._buffer.read(size)
  File "/usr/lib/python3.8/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/home/staticeel/.local/lib/python3.8/site-packages/isal/igzip.py", line 274, in read
    if not self._read_gzip_header():
  File "/usr/lib/python3.8/gzip.py", line 427, in _read_gzip_header
    raise BadGzipFile('Not a gzipped file (%r)' % magic)
gzip.BadGzipFile: Not a gzipped file (b'NC')

**Comment by arunhpatil** [comment]
Hi @tetty988 ,

Thank you.  It seems like the input file is not a ".fastq" nor a ".fastq.gz" file. Can you share the command you ran to derive this log, I want to look at the input file names, like `miRge3.0 -s input.fastq.gz`.  If you have the correct input FASTQ file, this error should not occur. I hope this helps.

Thank you,
Arun
