### ISSUE TITLE
UMI processing

### ISSUE THREAD

**Issue by lucascpantaleao** [mhalushka/miRge3.0#46]
Hi Arun,

now just trying to remove duplications using -qumi and getting a new error back:

"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/lucascp/.local/lib/python3.8/site-packages/mirge/libs/digest.py", line 346, in cutadapt
    umi_cut = umi.split(",")
AttributeError: 'NoneType' object has no attribute 'split'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/miRge3.0", line 8, in <module>
    sys.exit(main())
  File "/home/lucascp/.local/lib/python3.8/site-packages/mirge/__main__.py", line 103, in main
    pdDataFrame,sampleReadCounts,trimmedReadCounts,trimmedReadCountsUnique = baking(args, fastq_fullPath, base_names, workDir)
  File "/home/lucascp/.local/lib/python3.8/site-packages/mirge/libs/digest.py", line 143, in baking
    for each_list in fqres_pairs.result(): # retreving results from parallel execution
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
AttributeError: 'NoneType' object has no attribute 'split'

any idea what is up?

**Comment by arunhpatil** [comment]
Hi @lucascpantaleao,

Can you share the parameters used? Seems like the variable processing UMI has nothing to split. 

Arun

**Comment by lucascpantaleao** [comment]
miRge3.0 -s /home/lucascp/projects/miRNA/SLX-20055/SLX-20055.MIHT9.HCTGLDRXY.s_2.r_1.fastq -lib /home/lucascp/miRge3_Lib -on human -db mirgenedb -o output_dir -cpu 1 -a AACTGTAGGCACCATCAAT -qumi

**Comment by arunhpatil** [comment]
Hi @lucascpantaleao ,

Additional required argument is missing, `-umi`.  We need to specify number of nucleotides that specify UMI on both ends of the reads. Qiagen UMI, comes with standard 12 nucleotides UMI in the middle of two 3' adapter sequences. You just need to specify the parameter  -umi 0,12 (To trim 0 bases at 5′ and 12 bases at 3′). Note, this 12nt is the standard UMI length from Qiagen, you can change the length of UMI sequence if it is not 12 bp. This should solve the issue.

Commands:
`-qumi` has unique functionality to specifically extract the UMI sequence between the adapters sequence which is different from Illumina. Thus, it is required to specify qiagen parameter (-qumi), `case-1`, however, if you want to remove PCR duplicates then you need to add `-udd` as shown in `case-2`:

`case-1`
miRge3.0 -s /home/lucascp/projects/miRNA/SLX-20055/SLX-20055.MIHT9.HCTGLDRXY.s_2.r_1.fastq -lib /home/lucascp/miRge3_Lib -on human -db mirgenedb -o output_dir -cpu 1 -a AACTGTAGGCACCATCAAT -qumi -umi 0,12

`case-2`
miRge3.0 -s /home/lucascp/projects/miRNA/SLX-20055/SLX-20055.MIHT9.HCTGLDRXY.s_2.r_1.fastq -lib /home/lucascp/miRge3_Lib -on human -db mirgenedb -o output_dir -cpu 1 -a AACTGTAGGCACCATCAAT -qumi -umi 0,12 -udd

Thank you,
Arun.

**Comment by lucascpantaleao** [comment]
Looking perfect now. Thanks a lot Arun :)
