### ISSUE TITLE
TypeError in Summarizing and tabulating results on macOS

### ISSUE THREAD

**Issue by jofa123** [mhalushka/miRge3.0#47]
Hi,

miRge3.0 runs on macOS with Python 3.7.5. The example process runs without error and returns meaningful results. However, with own data, problems occur in the summarizing results part of the pipeline.

The following command results in the output below:

miRge3.0 -s 28-POS-Q-gel_S20_L002_R1_001.fastq.gz -lib . -a AACTGTAGGCACCATCAAT -on human -db miRBase -o output_dir -gff -cpu 1

bowtie version: 1.3.0
cutadapt version: 3.4
Samtools version: 1.15.1
Collecting and validating input files...

miRge3.0 will process 1 out of 1 input file(s).

Cutadapt finished for file 28-POS-Q-gel_S20_L002_R1_001 in 0.128 second(s)
Collapsing finished for file 28-POS-Q-gel_S20_L002_R1_001 in 0.0334 second(s)

Matrix creation finished in 0.043 second(s)

Data pre-processing completed in 0.2117 second(s)

Alignment in progress ...
Alignment completed in 11.4896 second(s)

Summarizing and tabulating results...
Traceback (most recent call last):
  File "/usr/local/bin/miRge3.0", line 10, in <module>
    sys.exit(main())
  File "/Users/job/Library/Python/3.7/lib/python/site-packages/mirge/__main__.py", line 114, in main
    summarize(args, workDir, ref_db, base_names, pdMapped, sampleReadCounts, trimmedReadCounts, trimmedReadCountsUnique)
  File "/Users/job/Library/Python/3.7/lib/python/site-packages/mirge/libs/summary.py", line 744, in summarize
    subpdMapped['miRNA_cbind'] = subpdMapped[['exact miRNA', 'isomiR miRNA']].apply(lambda x: ''.join(x), axis = 1)
  File "/Users/job/Library/Python/3.7/lib/python/site-packages/pandas/core/frame.py", line 6878, in apply
    return op.get_result()
  File "/Users/job/Library/Python/3.7/lib/python/site-packages/pandas/core/apply.py", line 180, in get_result
    return self.apply_empty_result()
  File "/Users/job/Library/Python/3.7/lib/python/site-packages/pandas/core/apply.py", line 220, in apply_empty_result
    return self.obj._constructor_sliced(r, index=self.agg_axis)
  File "/Users/job/Library/Python/3.7/lib/python/site-packages/pandas/core/series.py", line 305, in __init__
    data = sanitize_array(data, index, dtype, copy, raise_cast_failure=True)
  File "/Users/job/Library/Python/3.7/lib/python/site-packages/pandas/core/construction.py", line 465, in sanitize_array
    subarr = construct_1d_arraylike_from_scalar(value, len(index), dtype)
  File "/Users/job/Library/Python/3.7/lib/python/site-packages/pandas/core/dtypes/cast.py", line 1452, in construct_1d_arraylike_from_scalar
    subarr = np.empty(length, dtype=dtype)
TypeError: Cannot interpret '<attribute 'dtype' of 'numpy.generic' objects>' as a data type

Would you have any idea how to avoid this error?

Many thanks.

**Comment by jofa123** [comment]
Thanks a lot Arun - that worked for us :)
