### ISSUE TITLE
Sample data running error.

### ISSUE THREAD

**Issue by wan230114** [mhalushka/miRge3.0#6]
CMD:
```bash
miRge3.0 -s SRR772403.fastq,SRR772404.fastq,SRR772405.fastq,SRR772406.fastq -lib /home/chenjun/dataBase/miRge3_Lib -on human -db mirgenedb -o output_dir -gff -nmir -trf -ai -cpu 12 -a illumina
```

error logs:
```bash
cutadapt version: 2.7
Samtools version: 1.9
RNAfold version: 2.3.3
Collecting and validating input files...

miRge3.0 will process 4 out of 4 input file(s).

Cutadapt finished for file SRR772403 in 1.9251 second(s)
Collapsing finished for file SRR772403 in 0.017 second(s)

Cutadapt finished for file SRR772404 in 6.7914 second(s)
Collapsing finished for file SRR772404 in 0.2803 second(s)

Cutadapt finished for file SRR772405 in 11.5172 second(s)
Collapsing finished for file SRR772405 in 1.0486 second(s)

Cutadapt finished for file SRR772406 in 2.8867 second(s)
Collapsing finished for file SRR772406 in 0.9172 second(s)

Matrix creation finished in 0.3111 second(s)

Data pre-processing completed in 26.0883 second(s)

Alignment in progress ...
Alignment completed in 14.1082 second(s)

Summarizing and tabulating results...
The number of A-to-I editing sites for is less than 10 so that no heatmap is drawn.
Summary completed in 79.5822 second(s)

Predicting novel miRNAs


Performing prediction of novel miRNAs...
Start to predict
Traceback (most recent call last):
  File "/home/chenjun/software/linux_tools/miniconda3/envs/mirge3/bin/miRge3.0", line 33, in <module>
    sys.exit(load_entry_point('mirge3==0.0.2', 'console_scripts', 'miRge3.0')())
  File "/home/chenjun/software/linux_tools/miniconda3/envs/mirge3/lib/python3.8/site-packages/mirge3-0.0.2-py3.8.egg/mirge/__main__.py", line 141, in main
    predict_nmir(args, workDir, ref_db, base_names, pdUnmapped)
  File "/home/chenjun/software/linux_tools/miniconda3/envs/mirge3/lib/python3.8/site-packages/mirge3-0.0.2-py3.8.egg/mirge/libs/novel_mir.py", line 440, in predict_nmir
    screen_precusor_candidates(str(Path(outputdir2)), files, str(Path(outputdir2)/(files+"_features.tsv")), strFileOut, str(rnafoldCmdTmp))
  File "/home/chenjun/software/linux_tools/miniconda3/envs/mirge3/lib/python3.8/site-packages/mirge3-0.0.2-py3.8.egg/mirge/libs/screen_precusor_candidates.py", line 145, in screen_precusor_candidates
    upPrecusor = wholePrecusorNameContentDic[clusterName+':precusor_1']
KeyError: 'SRR772403:miRCluster_26_17:chr11:17432509_17432525-:precusor_1'
```

**Comment by wan230114** [comment]
Sorry, I found the reason for the error, and the problem was solved after reinstalling RNAfold manually
