### ISSUE TITLE
Cannot set a DataFrame with multiple columns to the single column miRNA_cbind

### ISSUE THREAD

**Issue by imranjesar** [mhalushka/miRge3.0#80]
miRge is abruptly stopping after alignment and shows an error for summarizing and tabulating results
below is the code i ran and the response i got, i tried the code with several modification but still getting the same error

miRge3.0 -s dht_treated_1.fastq.gz,dht_treated_2.fastq.gz,dht_treated_3.fastq.gz,etoh_treated_1.fastq.gz,etoh_treated_2.fastq.gz,etoh_treated_3.fastq.gz  -lib mirgelib/ -on human -db mirgenedb -gff -nmir -trf -ai -cpu 12 -a illumina 
/home/imran/anaconda3/envs/mirge3/lib/python3.8/site-packages/Bio/pairwise2.py:278: BiopythonDeprecationWarning: Bio.pairwise2 has been deprecated, and we intend to remove it in a future release of Biopython. As an alternative, please consider using Bio.Align.PairwiseAligner as a replacement, and contact the Biopython developers if you still need the Bio.pairwise2 module.
  warnings.warn(
bowtie version: 1.3.1
cutadapt version: 4.4
Samtools version: 1.6
RNAfold version: 2.6.2
Collecting and validating input files...

miRge3.0 will process 6 out of 6 input file(s).

Cutadapt finished for file dht_treated_1 in 3.4548 second(s)
Collapsing finished for file dht_treated_1 in 0.0951 second(s)

Cutadapt finished for file dht_treated_2 in 3.6683 second(s)
Collapsing finished for file dht_treated_2 in 0.9491 second(s)

Cutadapt finished for file dht_treated_3 in 3.8739 second(s)
Collapsing finished for file dht_treated_3 in 1.2447 second(s)

Cutadapt finished for file etoh_treated_1 in 4.0007 second(s)
Collapsing finished for file etoh_treated_1 in 1.5158 second(s)

Cutadapt finished for file etoh_treated_2 in 3.5539 second(s)
Collapsing finished for file etoh_treated_2 in 1.7891 second(s)

Cutadapt finished for file etoh_treated_3 in 3.8438 second(s)
Collapsing finished for file etoh_treated_3 in 2.0471 second(s)

Matrix creation finished in 0.4205 second(s)

Data pre-processing completed in 31.1077 second(s)

Alignment in progress ...
Alignment completed in 16.2217 second(s)

Summarizing and tabulating results...
Traceback (most recent call last):
  File "/home/imran/anaconda3/envs/mirge3/bin/miRge3.0", line 10, in <module>
    sys.exit(main())
  File "/home/imran/anaconda3/envs/mirge3/lib/python3.8/site-packages/mirge/__main__.py", line 166, in main
    summarize(args, workDir, ref_db, base_names, pdMapped, sampleReadCounts, trimmedReadCounts, trimmedReadCountsUnique)
  File "/home/imran/anaconda3/envs/mirge3/lib/python3.8/site-packages/mirge/libs/summary.py", line 744, in summarize
    subpdMapped['miRNA_cbind'] = subpdMapped[['exact miRNA', 'isomiR miRNA']].apply(lambda x: ''.join(x), axis = 1)
  File "/home/imran/anaconda3/envs/mirge3/lib/python3.8/site-packages/pandas/core/frame.py", line 3940, in __setitem__
    self._set_item_frame_value(key, value)
  File "/home/imran/anaconda3/envs/mirge3/lib/python3.8/site-packages/pandas/core/frame.py", line 4094, in _set_item_frame_value
    raise ValueError(
ValueError: Cannot set a DataFrame with multiple columns to the single column miRNA_cbind

**Comment by arunhpatil** [comment]
Hi @imranjesar,

It seems like the adapter sequence is incorrect. You can check the FAQ on how to detect adapters in your sample [here](https://mirge3.readthedocs.io/en/latest/faqs.html#is-there-any-way-to-skip-the-adaptor-trimming-process-and-how-to-determine-adapter-sequence-of-a-run). Alternatively, if you can share the subset of data, I can have a look. 

Let me know if this works out. 

Thank you,
Arun.

**Comment by imranjesar** [comment]
Hi @arunhpatil 

Thank you for pointing out the problem, I removed the adapters using fastp, and then miRge3.0 ran successfully for my data

I appreciate your help 

Thanks

Imran

**Comment by arunhpatil** [comment]
Hi @imranjesar 

I am glad it worked. Also note that, miRge3.0 can trim adapters, and use of correct adapter sequences determines the precise small-RNA annotations and quantifications. 

Thank you,
Arun.
