### ISSUE TITLE
Python bug

### ISSUE THREAD

**Issue by Cristinex** [mhalushka/miRge3.0#99]
Hi,
Thank you for your development of miRge3.0. Since I failed to use version 0.1.2 and 0.1.3 with cutadapt issue, I downloaded a version 0.09. However, it failed to output after alignment due to python error. I cannot find where the '+' locate at. Could you please help me to solve the following problem?

"""

bowtie version: 1.0.0
cutadapt version: 4.9
Samtools version: 1.3.1
Collecting and validating input files...

miRge3.0 will process 6 out of 6 input file(s).

Cutadapt finished for file CL100222353_L01_25 in 171.9839 second(s)
Collapsing finished for file CL100222353_L01_25 in 22.1784 second(s)

Cutadapt finished for file CL100222353_L01_26 in 160.2769 second(s)
Collapsing finished for file CL100222353_L01_26 in 47.2628 second(s)

Cutadapt finished for file CL100222353_L01_27 in 198.9179 second(s)
Collapsing finished for file CL100222353_L01_27 in 70.4865 second(s)

Cutadapt finished for file CL100222353_L02_28 in 206.2919 second(s)
Collapsing finished for file CL100222353_L02_28 in 103.9097 second(s)

Cutadapt finished for file CL100222353_L02_29 in 229.1622 second(s)
Collapsing finished for file CL100222353_L02_29 in 138.1642 second(s)

Cutadapt finished for file CL100222353_L02_30 in 231.3351 second(s)
Collapsing finished for file CL100222353_L02_30 in 171.4097 second(s)

Matrix creation finished in 16.6116 second(s)

Data pre-processing completed in 1827.6381 second(s)

Alignment in progress ...
Alignment completed in 918.8656 second(s)

Summarizing and tabulating results...
Traceback (most recent call last):
  File "/data/home/grp-huangxd/caixiaoxuan/sub_conda/miRge3.0/bin/miRge3.0", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/data/home/grp-huangxd/caixiaoxuan/sub_conda/miRge3.0/lib/python3.11/site-packages/mirge/__main__.py", line 166, in main
    summarize(args, workDir, ref_db, base_names, pdMapped, sampleReadCounts, trimmedReadCounts, trimmedReadCountsUnique)
  File "/data/home/grp-huangxd/caixiaoxuan/sub_conda/miRge3.0/lib/python3.11/site-packages/mirge/libs/summary.py", line 698, in summarize
    empty_list[col_vars[element]] = {file_name:pdMapped[pdMapped[col_in].astype(bool)][file_name].values.sum()}
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/home/grp-huangxd/caixiaoxuan/sub_conda/miRge3.0/lib/python3.11/site-packages/numpy/core/_methods.py", line 49, in _sum
    return umr_sum(a, axis, dtype, out, keepdims, initial, where)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unsupported operand type(s) for +: 'float' and 'str'

"""

**Comment by arunhpatil** [comment]
Hi @Cristinex,

This is no problem. I guess the issue is with counts being zero, which in-turn occured due to incorrect adapter sequence. Can you check the parameters of adapter sequence? I can check this error/adapters, provided if you can send a sample subset FASTQ file.  

Thank you,
Arun.
